### PR TITLE
[WIP] Auto generate Prison API types

### PR DESCRIPTION
**Pull request by jsrobertson**
## Release checklist

[Release process documentation](../doc/how-to/perform-a-release.md)

As part of our continuous deployment strategy we must ensure that this work is
ready to be released once merged.

### Pre-merge

- [ ] There are changes required to the Accredited Programmes API for this change to work...
  - [ ] ... and they have been released to production already

### Post-merge

- [ ] This adds, extends or meaningfully modifies a feature...
  - [ ] ... and I have written or updated an end-to-end test for the happy path in the [Accredited Programmes E2E repo](https://github.com/ministryofjustice/hmpps-accredited-programmes-e2e)
- [ ] This makes new expectations of the API...
  - [ ] ... and I have notified the API developer(s) of changes to the contract tests (Pact), or the API is already compliant
- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-preprod-environment) release to preprod
- [ ] [Manually approve](../doc/how-to/perform-a-release.md#releasing-to-the-production-environment) release to prod

### CODE REVIEW

**Comment by Gweaton** [comment]
Looks like this was done in https://github.com/ministryofjustice/hmpps-accredited-programmes-ui/pull/408 - closing this one

**Comment by yndajas** [comment]
@Gweaton this wasn't done in #408. This PR is for setting up a GitHub action to open Prison API type update PRs automatically. #408 just mentioned this PR to say that hopefully we won't have to keep updating those types in random PRs for too long

**Comment by Gweaton** [comment]
@yndajas Oops! This'll teach me to meddle in the UI codebase again... I skimmed this and thought it was the script for generating the types, rather than the workflow...

**Comment by jsrobertson** [comment]
Closing until post release

**Pull request closed without merging**
